name: radiotray-ng
summary: An Internet radio player for Linux
description: Simple Internet Radio Player Radiotray-NG runs in the system tray allowing you to select and play configured radio stations.
grade: stable
confinement: strict
adopt-info: radiotray-ng
architectures:
  - build-on: amd64

base: core18

parts:
  radiotray-ng-wrapper:
    plugin: dump
    after: [radiotray-ng]
    source: snap/local
    organize:
      radiotray-ng-wrapper.sh: usr/bin/radiotray-ng-wrapper.sh

  radiotray-ng:
    plugin: nil
    after: [desktop-gtk3]
    override-build: |
      set -x
      snapcraftctl build
      # Get the latest releases json
      wget --quiet https://api.github.com/repos/ebruck/radiotray-ng/releases -O releases.json
      # Get the version from the tag_name and the download URL (for Ubuntu 18.04)
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      DEB_URL=$(grep browser_download releases.json | grep "${VERSION}" | grep deb | cut -d'"' -f4 | grep 18.04)
      DEB=$(basename "${DEB_URL}")
      echo "Downloading ${DEB_URL}..."

      # DEBUG DEBUG DEBUG
      DEB_URL=http://192.168.31.44:8080/radiotray-ng_0.2.6-dev_amd64.deb

      wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      echo "Unpacking ${DEB}..."
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f releases.json 2>/dev/null
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}" 2>/dev/null
      snapcraftctl set-version "$VERSION"
    build-packages:
      - dpkg
      - jq
      - wget
    stage-packages:
      - libbsd0
      - libcurl4
      - libjsoncpp1
      - libxdg-basedir1
      - libnotify4
      - libglibmm-2.4-1v5
      - libboost-filesystem1.65.1
      - libboost-system1.65.1
      - libboost-log1.65.1
      - libboost-thread1.65.1
      - libboost-program-options1.65.1
      - libgstreamer1.0-0
      - libappindicator3-1
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libwxgtk3.0-0v5
      - libgpm2
  
  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all
    - xdg-user-dirs
    - ibus-gtk3
    - libibus-1.0-5
    - fcitx-frontend-gtk3  
#passthrough:
#  layout:
#    /usr/share/radiotray-ng:
#        bind: $SNAP/usr/share/radiotray-ng    

apps:
  radiotray-ng:
    desktop: usr/share/applications/radiotray-ng.desktop
    command: desktop-launch $SNAP/usr/bin/radiotray-ng-wrapper.sh
    environment:
      LC_ALL: C.UTF-8  
    plugs:
      - unity7
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - pulseaudio
      - x11
      - wayland

slots:
  dbus-radiotray-ng:
    interface: dbus
    bus: session
    name: com.github.radiotray_ng
